name: Docker CI Basic

on: [push]

jobs: 
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run Docker container
      run: docker run --rm my-app

    - name: Show available images
      run: docker images

    - name: Run container in background
      run: docker run -d --name bg-test alpine sleep 60

    - name: List running containers
      run: docker ps

    - name: Stop and remove container
      run: |
        docker stop bg-test
        docker rm bg-test

    - name: Run with environment variable
      run: docker run --rm APP_ENV=ptoduction my-app
